language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: CCgY/xX00Cmvz3RRSvFD+RFvOgjtmlCRrKzNAvuhWENx8N0dQS9lI2YJUuLLOuQjA8nahiO37VjKmqcw20fxprNah0DiqOXU5WKJLaFeRQ7XiTEpwjEYZ51WSYA6Tn9Vvlu83RHohVUU/qZRNuA6xVR2Wz2XTfFAPoj3zA7qL7PAhT8fHGxSCUbPGb7ZR0fUx/v6KoQgU2QoJj13k3M5VlTBUIjOODGuLtT/ZxZ/LDKtjU8w3YY4DTBgbv53J1aFEJPb8FpOjwHL+j9TBhKpcuPPxGNAOQ6F7DbEOjE068/e4940uTIGHoqQpmPZL662RQvK/JTF95IizKC0GTpJRVOnaA+BiFy42HT7VHWzBZjcBb3mEMSyiBkOIoPRhHLDn75DPUloFkh7AJoDeFNzoTuziCwZ9R5gCdFOeMXVKA8mWc985ZVQiQHGm1zePmdnZi/mxTLFT59OKNNKAZhR0VtEe933cJhQ/FN7GgGY1bXJwE6q3MRHNCgwqmCp5tYUtK/+ni6cf3Nn459RYYW0yBOYaXv6oe118vaB+q/I4Q/huR0a1zXHajw0C/6hV7U+2UUKNEFb5uWo++ws4qKzBvO54+h7ErlDAuNbRNHWL6o94CK5/0TlzOIa3Ha1nrC/ThfvupBK9fXvw07ts4HMF4bO64oaLarGqRqfdFn2wfk=
  app: safe-cliffs-7475
  on:
    repo: Unconditional-Chocolate/mealplan
