language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: sMBS54etWB7L+BTogbEN5lky+TYdeg+bgUqDEvsNjoX+VSeInTCOjobsZYn3balCboZf2so7W2kojmjWLeb4Dd494ARxFyYOxBlNZv7ilmTS3SpTa9msdUwSlu+TD0mlw6z62pGDM7krpBwQuuKa7CxHFV484yzXk8utany1m+Bdkfbkx8LCVHVuSCtgUiYRHgc0T6d6N2B80x7vXOFal93fPsPM98uW1o5zH/Wbgo4aCgViR3WfM6KcNAp5ifubOMP+vbjeMdFUp3Ava9gyT+LBihfcuEMMzV3bgj93YdZe/j25Pu2zpq98WPfNbC8r3YMMCgiSh49OUqJ6Rd4/eS2ZfRnfJ9YvWymZBJrxnZFkHxuSH6Z7Rhm33KEYF2xyC4x4V6JtdAkGxvYQF1dXHQUQV9HedIggkWREVKUExjKj0zR6lfdzNWtOGI7gEB7n0PmGS6WE2pwvgcxhPPQo2l5rg+Z3SKhUzJqsPggZdcfwS5dyc5JzMm/KwqIqVPMwas4AeJMRBPN8k/KT6Vp/Tf383r3NCgMPRtJAqsgDm9/yFIC+BWwUjSOODnimH6GW3xvu3JSR+nLJB/OSwRdAfeSHurXhk0D5A3uPgBsmiq3rsqcJUmdyfQpLwqASA/glDI5tgl1RtT28jg1Vg34wQ/bSGKdn3HO0rUNkj5VKEDU=
  app: safe-cliffs-7475
